Support the explicit API mode when generating Dagger factories
square/anvil pull request #145
Opened 2020-10-18 16:34 UTC by marcellogalhardo

Anvil uses KotlinPoet to generate the Dagger factories in which in the [latest version 1.7.0](https://github.com/square/kotlinpoet/blob/master/docs/changelog.md): _"Generated code is now compatible with the explicit API mode by default."_.

This PR:
- Updates [KotlinPoet to 1.7.1](https://github.com/square/kotlinpoet/releases/tag/1.7.1), which fixes: [Cannot use KotlinPoet version `1.7.0` with Java 8](https://github.com/square/kotlinpoet/issues/999).
- Updates the sample app to use explicit API mode in the `:sample:scopes` and `:sample:library` modules to show its usage, `:sample:app` module is untouched as it is not a "library" module. Let me know if you think this should not done and I can revert this commit.

2020-10-25 10:54 UTC, marcellogalhardo commented
Updated the PR to use KotlinPoet 1.7.2.

2020-10-25 19:45 UTC, vRallev requested changes
I'm so sorry for the delay. This PR is great. Could I ask you to enable the explicit API mode in the `:integration-tests:*` module rather than the sample? The sample is supposed to be closer to the real world and many projects won't enable the explicit API mode. On the other side, that's exactly the purpose of the integration tests.

2020-10-26 07:25 UTC, marcellogalhardo commented
Hey @vRallev - no worries. Right, I dropped the changes on `:sample` and converted all modules from `:integration_tests` to Explicit API Mode as you requested. Thanks for the review!

2020-10-26 16:13 UTC, vRallev approved these changes

2020-10-26 16:13 UTC, merged